E_shopper/E_shopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
    path('category/', include('category_app.urls')),
    path('product/',include('product_app.urls')),
    path('user/',include('user_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('order/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_shopper/base_app/urls.py
from django.contrib import admin
from django.urls import path,include
from base_app import views

urlpatterns = [

    path('', views.baseview),
    path('home/',views.homeview,name='home'),
    
]

E_shopper/user_app/urls.py
from django.contrib import admin
from django.urls import path
from user_app.views import *

app_name = 'user_app'

urlpatterns = [
    
    # signup handle
    path('signup/', signupView, name='signup'),
    path('signuphandle', handelSignup, name='signuphandle'),

    # login handle
    path('login/', loginView, name='login'),
    path('loginhandle', handleLogin, name='loginhandle'),

    # logout handle
    path('logouthandle',logouthandle, name='logouthandle'),

    # show profile 
    path('profile',profileView,name='profile'),

    # update_profile_info
    path('update_personal_info/', update_personal_info, name='update_personal_info'),

    # update email
    path('update_email/', update_email,name='update_email'),

    # update contact
    path('update_contact/', update_contact, name='update_contact'),

    # add new address
    path('add_address/', add_address, name='add_address'),

    # edit address
    path('edit_address/<int:address_id>/', edit_address, name='edit_address'),

    # delete address
    path('delete_address/<int:address_id>/', delete_address,name='delete_address'),

]

E_shopper/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=10)
    firstname = models.CharField(max_length=100, blank=True)
    lastname = models.CharField(max_length=100, blank=True)
    GENDER_CHOICE  = (
        ('M','Male'),
        ('F','Female'),
    )
    gender = models.CharField(max_length=1,choices=GENDER_CHOICE, blank=True)
    
class UserAddress(models.Model):    
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    contact = models.CharField(max_length=10)
    pincode = models.CharField(max_length=10)
    locality = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=50)
    STATE_CHOICE = (
        ('Arunachal Pradesh','Arunachal Pradesh'),
        ('Andman & Nicobar','Andman & Nicobar'),
        ('Assam','Assam'),
        ('Bihar','Bihar'),
        ('Chandigarh','Chandigarh'),
        ('Chattisgadh','Chattisgadh'),
        ('Dadra Nagar','Dadra Nagar'),
        ('Daman & Diu','Daman & Diu'),
        ('Delhi','Delhi'),
        ('Goa','Goa'),
        ('Gujrat','Gujrat'),
        ('Haryana','Haryana'),
        ('Himachal Pradesh','Himachal Pradesh'),
        ('Jammu','Jammu'),
        ('Jarkhand','Jarkhand'),
        ('Karnataka','Karnataka'),
        ('Kerala','Kerala'),
        ('Ladakh','Ladakh'),
        ('Madhya Pradesh','Madhya Pradesh'),
        ('Manipur','Manipur'),
        ('Maharashtra','Maharashtra'),
        ('Meghalaya','Meghalaya'),
        ('Mizoram','Mizoram'),
        ('Nagaland','Nagaland'),
        ('Odhisha','Odhisha'),
        ('Punjab','Punjab'),
        ('Rajasthan','Rajasthan'),
        ('Sikkim','Sikkim'),
        ('Tripura','Tripura'),
        ('Tamil Nadu','Tamil Nadu'),
        ('Telgana','Telgana'),
        ('Utar Prades','Utar Prades'),
        ('Utrakhand','Utrakhand'),
        ('West Benagal','West Benagal'),
    )
    state  = models.CharField(max_length=255,choices=STATE_CHOICE)
    landmark = models.CharField(max_length=100)
    optionalnumber = models.CharField(max_length=10,blank=True)
    ADDRESS_TYPE = (
        ('Home','HOME'),
        ('Work','WORK'),
    )
    addresstype = models.CharField(max_length=10,choices=ADDRESS_TYPE)

E_shopper/user_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login ,logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse,HttpResponse
from user_app.models import UserProfile,UserAddress
from order_app.models import OrderModel

# Create your views here.
# signup page
def signupView(request):  
     # Render the signup.html template
    return render(request,'user_app/signup.html')

# handle signup
def handelSignup(request):
    if request.method == "POST":
         # Get the POST values from the form
        username = request.POST['name']
        email = request.POST['email']
        contact = request.POST['contact']
        password1 = request.POST['pass']
        password2 = request.POST['re_pass']
        
        # Check if password1 and password2 match
        if password1 == password2:
            
            # Check if a user with the same email or username already exists
            data = User.objects.filter(Q(email=email) | Q(username=username)) 
            if len(data) <= 0:
                
                # Create a new User instance
                myuser = User.objects.create_user(username, email, password1)
                
                # Create a UserProfile instance and associate it with the user
                user_profile = UserProfile.objects.create(user=myuser, contact=contact)
                
                # Render a success message
                return render(request,'user_app/login.html',{'messagekey':'Registration Successful!'})
            else:
                # Render a message for existing user
                return render(request,'user_app/signup.html',{'messagekey':'User Already Exists'})
        else:
            # Render a message for password mismatch
            return render(request,'user_app/signup.html',{'messagekey':'Password Does Not Match'})
    else:
        # Return a 404 response for non-POST requests
        return HttpResponse('404 - Not Found')

# login page
def loginView(request):
    # fetch detail from post page for return after login
    retpath = request.GET.get('retpath', '')
    subcatslug = request.GET.get('subcatslug', '')
    productslug = request.GET.get('productslug', '')
    # print(retpath)
    # print(subcatslug)
    # print(productslug)
    context={
        'retpath':retpath,
        'subcateslug':subcatslug,
        'productslug':productslug,
    }
    return render(request,'user_app/login.html',context)

# login handle
def handleLogin(request):
    if request.method == "POST":
        # retrive from login form
        retpath = request.POST.get('retpath', '')
        subcatslug = request.POST.get('subcatslug', '')
        productslug = request.POST.get('productslug', '')

        # print("repath:",retpath)
        # print("subcatslug:",subcatslug)
        # print('productslug',productslug)

        loginusername = request.POST['loginusername']
        loginpassword = request.POST['loginpass']

        user = authenticate(username = loginusername, password = loginpassword)

        if user is not None:
            # If the user is authenticated, log them in and redirect to the home page
            login(request,user)
            print('login successfully')
            # check in url and then redirect to return page
            if retpath == "prolog":
                return redirect('product_app:products',subcatslug=subcatslug)
            elif retpath == 'prodet':
                return redirect('product_app:productdetail',productslug=productslug)
            elif retpath == 'checkout':
                return redirect('cart_app:checkout')
            return redirect('home')
        else:
            # If authentication fails, render the login page with an error message
            return render(request,'user_app/login.html', {'messagekey':" Inavalid Credentials !"})
    # If the request method is not POST, return a 404 response
    return HttpResponse('404 - Not Found')

# logout handle
def logouthandle(request):
    logout(request)
    print("logout")
    return redirect('home')


# profile page view
def profileView(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    user_addresses = UserAddress.objects.filter(user=request.user)
    my_order = OrderModel.objects.filter(user=request.user).order_by('-id')
    # print("my order: ",my_order)

    if request.method == 'POST':
        user_profile.firstname = request.POST.get('firstname')
        user_profile.lastname = request.POST.get('lastname')
        user_profile.contact = request.POST.get('contact')
        user_profile.gender = request.POST.get('gender')
        user_profile.save()
    
    context = {
        'user_profile': user_profile,
        'user_addresses': user_addresses,
        'my_order' : my_order,
    }
    return render(request,'user_app/profile.html',context)

@login_required
# update profile personal detail
def update_personal_info(request):
    user_profile =  UserProfile.objects.get(user=request.user) 

    # Update the user's first name, last name, and gender
    if request.method == 'POST':
        user_profile.firstname = request.POST.get('firstname')
        print("update",user_profile.firstname)
        user_profile.lastname = request.POST.get('lastname')
        print("update",user_profile.firstname)
        user_profile.gender = request.POST.get('gender')
        print("update",user_profile.gender)
        
        # Save the updated profile
        user_profile.save()
    return redirect('user_app:profile')

# update profile email 
@login_required
def update_email(request):

    # Update the user's email
    if request.method == 'POST':
        new_email = request.POST.get('email')
        print("new_email: ",new_email)
        user = request.user
        user.email = new_email
        print("database email:",user.email)
        # Save the updated email
        user.save()
    
    return redirect('user_app:profile')

# update profile contact
@login_required
def update_contact(request):
    user_profile = UserProfile.objects.get(user=request.user)

    # Update the user's contact
    if request.method == 'POST':
        user_profile.contact = request.POST.get('mobileNumber')
        print("update contact: ",user_profile.contact)

        # Save the user contact
        user_profile.save()
    
    return redirect('user_app:profile')

# add address to user profile
@login_required
def add_address(request):
    retpath = request.GET.get('retpath', '')
    if request.method == 'POST':
        name = request.POST.get('name')
        # print(name)
        contact = request.POST.get('mobile')
        # print(contact)
        pincode = request.POST.get('pincode')
        # print(pincode)
        locality = request.POST.get('locality')
        # print(locality)
        address = request.POST.get('address')
        # print(address)
        city = request.POST.get('city')
        # print(city)
        state = request.POST.get('state')
        # print(state)
        landmark = request.POST.get('landmark')
        # print(landmark)
        optionalnumber = request.POST.get('optionalNumber')
        # print(optionalnumber)
        addresstype = request.POST.get('addressType')
        # print(addresstype)

        address = UserAddress(
            user = request.user,
            name = name,
            contact = contact,
            pincode = pincode,
            locality = locality,
            address = address,
            city = city,
            state = state,
            landmark = landmark,
            optionalnumber = optionalnumber,
            addresstype = addresstype
        )
        address.save()
        
    if retpath == "checkout":
            return redirect('cart_app:checkout')

    return redirect('user_app:profile')

# edit user profile particular existed addresses
@login_required
def edit_address(request,address_id):
    retpath = request.GET.get('retpath', '')
    address = get_object_or_404(UserAddress, id=address_id, user=request.user)
    if request.method == 'POST':

        address.name = request.POST.get('name')  # Use request.POST.get() with a default value
        address.contact = request.POST.get('mobile')
        address.pincode = request.POST.get('pincode')
        address.locality = request.POST.get('locality')
        address.address = request.POST.get('address')
        address.city = request.POST.get('city')
        address.state = request.POST.get('state')
        address.landmark = request.POST.get('landmark')
        address.optionalnumber = request.POST.get('optionalNumber')
        address.addresstype = request.POST.get('addressType')

        address.save()

        if retpath == "checkout":
            return redirect('cart_app:checkout')

        return redirect('user_app:profile')
    
# delete user profile particular address
@login_required
def delete_address(request,address_id):
    retpath = request.GET.get('retpath', '')
    address = get_object_or_404(UserAddress, id=address_id, user=request.user)
    
    address.delete()

    if retpath == "checkout":
        return redirect('cart_app:checkout')

    return redirect('user_app:profile')

E_shopper/user_app/templates/user_app/login.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
            </div>
            <!--signup section-->
            <div class="col-sm-4 col-sm-offset-1 ">
                <!--login form-->
                <div class="login-form">
                    <h2>Login to your account</h2>
                    <form method="post" action="{% url 'user_app:loginhandle' %}">
                        {% csrf_token %}
                        <input type="hidden" name="retpath" value="{{ retpath }}">
                        <input type="hidden" name="subcatslug" value="{{ subcateslug }}">
                        <input type="hidden" name="productslug" value="{{ productslug }}">
                        
                        <input type="text" name="loginusername" id="loginusername" placeholder="Username" style="color: black;"/>
                        <input type="password" name="loginpass" id="loginpass" placeholder="Password" />
                        <span>
                            <input type="checkbox" class="checkbox"> Keep me signed in
                        </span>
                        <button type="submit" value="submit" class="btn btn-default">Login</button>
                        <br>
                        <h5>Don't have accounr? <a href="{% url 'user_app:signup' %}">Create Account</a></h5>
                    </form>
                    {% if messagekey %}
                    <script>alert("{{ messagekey }}")</script>
                    {% endif %}
                </div>
                <!--/login form-->
            </div>
            <!--signup section-->
        </div>
    </div>
</section>
{% endblock content %}

E_shopper/user_app/templates/user_app/signup.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
            </div>
            <!--signup section-->
            <div class="col-sm-4 col-sm-offset-1 ">
                <div class="signup-form">
                    <h2>New User Signup!</h2>
                    <form method="post" action="{% url 'user_app:signuphandle' %}">
                        {% csrf_token %}
                        <input type="text" name="name" id="name" placeholder="Your Name" style="color: black;"
                            required />
                        <input type="email" name="email" id="email" placeholder="Email Address" style="color: black;"
                            required />
                        <input type="number" maxlength="10" name="contact" id="contact" placeholder="Contact No"
                            style="color: black;" />
                        <input type="password" name="pass" id="pass" placeholder="Password" style="color: black;"
                            required />
                        <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"
                            style="color: black;" required />
                        <button class="btn btn-default" type="submit" value="Submit"
                            style="background: #FE980F; color: #FFFFFF; font-family: 'Roboto', sans-serif; width: 35%;">
                            Sign Up
                        </button>
                        <br>
                        <h5>Already have accounr? <a href="{% url 'user_app:login' %}">Login</a></h5>
                    </form>
                    {% if messagekey %}
                    <script>alert("{{ messagekey }}")</script>
                    {% endif %}
                </div>
            </div>
            <!--signup section-->
        </div>
    </div>
</section>
{% endblock content %}