E_shopper/E_shopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
    path('category/', include('category_app.urls')),
    path('product/',include('product_app.urls')),
    path('user/',include('user_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('order/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_shopper/base_app/urls.py
from django.contrib import admin
from django.urls import path,include
from base_app import views

urlpatterns = [

    path('', views.baseview),
    path('home/',views.homeview,name='home'),
    
]

E_shopper/cart_app/urls.py
from django.contrib import admin
from django.urls import path
from cart_app.views import *

app_name = 'cart_app'

urlpatterns = [
    # for add items in cart
    path('add_to_cart/<slug:productslug>',add_to_cart, name='add_to_cart'),
    # for cart page
    path('usercart', cartView, name='cart'),
    path('deleteitem/<int:item_id>', delete_cart_item, name='delete_cart_item'),
    path('clearcart', clear_cart, name='clear_cart'),
    path('increment_cart_quantity/<int:item_id>/', increment_cart_quantity, name='increment_cart_quantity'),
    path('decrement_cart_quantity/<int:item_id>/', decrement_cart_quantity, name='decrement_cart_quantity'),

    # for checkout page
    path('checkout/', checkoutView, name='checkout'),


]

E_shopper/product_app/urls.py
from django.contrib import admin
from django.urls import path
from product_app.views import ProductView,ProductDetailView

app_name = 'product_app'

urlpatterns = [
    path('products/<slug:subcatslug>', ProductView, name='products'),
    path('productdetail/<slug:productslug>',ProductDetailView, name = 'productdetail'),
    # ... other product app URL patterns ...
]

E_shopper/user_app/urls.py
from django.contrib import admin
from django.urls import path
from user_app.views import *

app_name = 'user_app'

urlpatterns = [
    
    # signup handle
    path('signup/', signupView, name='signup'),
    path('signuphandle', handelSignup, name='signuphandle'),

    # login handle
    path('login/', loginView, name='login'),
    path('loginhandle', handleLogin, name='loginhandle'),

    # logout handle
    path('logouthandle',logouthandle, name='logouthandle'),

    # show profile 
    path('profile',profileView,name='profile'),

    # update_profile_info
    path('update_personal_info/', update_personal_info, name='update_personal_info'),

    # update email
    path('update_email/', update_email,name='update_email'),

    # update contact
    path('update_contact/', update_contact, name='update_contact'),

    # add new address
    path('add_address/', add_address, name='add_address'),

    # edit address
    path('edit_address/<int:address_id>/', edit_address, name='edit_address'),

    # delete address
    path('delete_address/<int:address_id>/', delete_address,name='delete_address'),

]

E_shopper/base_app/models.py
from django.db import models

# Create your models here.

E_shopper/base_app/views.py
from django.shortcuts import render
from category_app.views import CategoryView,Cat_Subcat_Nav_View

# Create your views here.
def baseview(request):
    return render(request,'base_app/base.html')

def homeview(request):
    categories = CategoryView()
    cat_subcat_for_nav = Cat_Subcat_Nav_View()
    # print("categories",categories)
    context = {
        'categories': categories,
        'cat_sub_nav' : cat_subcat_for_nav
    }
    return render(request,'base_app/home.html',context)

E_shopper/base_app/templates/base_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-Shopper</title>

	<link rel="icon" href="data:,">
	<!-- css link -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    {% comment %} <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}" type="text/css"> {% endcomment %}
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}" type="text/css">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}" type="text/css">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}" type="text/css">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}" type="text/css">
	<!-- end css link -->

	<!-- js link -->
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
	<!-- end js link -->
</head>

<body>
	<!--header-->
	<header id="header">

		<!-- header_top -->
		<!-- <div class="header_top">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		<!-- header_top -->
		
		<!--header-middle-->
		<div class="header-middle">
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="#"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								
								

								<!-- <li><a href="#"><i class="fa fa-user"></i> Profile</a></li> -->
								<!-- <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li> -->
								<!-- Check if user is authenticated -->
								{% if user.is_authenticated %}
								<li><a href="#" style="pointer-events: none;"><p style="color:black;">Welcome, {{ user.username |capfirst }}!</p></a></li>
								<li><a href="{% url 'cart_app:checkout' %}"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="{% url 'cart_app:cart' %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><a href="{% url 'user_app:profile' %}"><i class="fa fa-user"></i> Profile</a></li>
								<li><a href="{% url 'user_app:logouthandle' %}"><i class="fa fa-long-arrow-right"></i> Logout</a></li>
								{% else %}
								<li><a href="{% url 'cart_app:cart' %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><a href="{% url 'user_app:signup' %}"><i class="fa fa-sign-in"></i> Sign up</a></li>
								<li><a href="{% url 'user_app:login' %}"><i class="fa fa-lock"></i> Login</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--header-middle-->
		
		<!--header-bottom-->
		<div class="header-bottom">
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'home' %}" class="active">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'product_app:products' 'all' %}">Products</a></li>
										<li><a href="{% url 'cart_app:checkout' %}">Checkout</a></li> 
										<li><a href="{% url 'cart_app:cart'%}">Cart</a></li> 
										<li><a href="{% url 'user_app:login' %}">Login</a></li> 
                                    </ul>
                                </li> 
								<!-- <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li>  -->
								<!-- <li><a href="404.html">404</a></li> -->
								<li><a href="#contact-us.html">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/header-bottom-->
	
	</header>
	<!--/header-->
	
	<!--  dynamic content -->
	{% block content%}
	{% endblock %}
	<!-- dynamic content -->
	
	<!--Footer-->
	<footer id="footer">
		<!-- <div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png' %}images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png' %}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<!-- <li><a href="#">Online Help</a></li> -->
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<!-- <li><a href="#">Change Location</a></li> -->
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<!-- <li><a href="#">Gift Cards</a></li> -->
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<!-- <li><a href="#">Billing System</a></li> -->
								<!-- <li><a href="#">Ticket System</a></li> -->
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<!-- <li><a href="#">Store Location</a></li> -->
								<!-- <li><a href="#">Affillate Program</a></li> -->
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2022 E-SHOPPER Inc. All rights reserved.</p>
					<!-- <p class="pull-right">Designed by <span><a target="_blank" href="#">xyz</a></span></p> -->
				</div>
			</div>
		</div>
		
	</footer>
	<!--/Footer-->

</body>
</html>