E_shopper/E_shopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
    path('category/', include('category_app.urls')),
    path('product/',include('product_app.urls')),
    path('user/',include('user_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('order/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_shopper/base_app/urls.py
from django.contrib import admin
from django.urls import path,include
from base_app import views

urlpatterns = [

    path('', views.baseview),
    path('home/',views.homeview,name='home'),
    
]

E_shopper/cart_app/urls.py
from django.contrib import admin
from django.urls import path
from cart_app.views import *

app_name = 'cart_app'

urlpatterns = [
    # for add items in cart
    path('add_to_cart/<slug:productslug>',add_to_cart, name='add_to_cart'),
    # for cart page
    path('usercart', cartView, name='cart'),
    path('deleteitem/<int:item_id>', delete_cart_item, name='delete_cart_item'),
    path('clearcart', clear_cart, name='clear_cart'),
    path('increment_cart_quantity/<int:item_id>/', increment_cart_quantity, name='increment_cart_quantity'),
    path('decrement_cart_quantity/<int:item_id>/', decrement_cart_quantity, name='decrement_cart_quantity'),

    # for checkout page
    path('checkout/', checkoutView, name='checkout'),


]

E_shopper/payment_app/urls.py
# dj_razorpay/urls.py

from django.contrib import admin
from django.urls import path
from payment_app import views

app_name = 'payment_app'

urlpatterns = [
    
	path('initialize_razorpay/<int:order_id>/', views.initialize_razorpay, name='initialize_razorpay'),
    path('razorpay_payment_success/', views.razorpay_payment_success, name='razorpay_payment_success'),
	
]

E_shopper/product_app/urls.py
from django.contrib import admin
from django.urls import path
from product_app.views import ProductView,ProductDetailView

app_name = 'product_app'

urlpatterns = [
    path('products/<slug:subcatslug>', ProductView, name='products'),
    path('productdetail/<slug:productslug>',ProductDetailView, name = 'productdetail'),
    # ... other product app URL patterns ...
]

E_shopper/payment_app/models.py
from django.db import models

# Create your models here.

E_shopper/payment_app/views.py
from django.shortcuts import render
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest,Http404
from order_app.models import OrderModel,OrderItem
from cart_app.models import CartModel,CartItemModel


# authorize razorpay client with API Keys.
razorpay_client = razorpay.Client(
	auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))


def initialize_razorpay(request, order_id):
    order = OrderModel.objects.get(id=order_id)
    user = request.user
    print("intial:",user)
    cart = CartModel.objects.get(user=user)
    cart_items = cart.items.all()
    cart_item = CartItemModel.objects.filter(user=user)

    # print(order)
    order_itemm = OrderItem.objects.filter(order=order)
    # print("order_item: ",order_itemm)
    total_order_amount = order.total_amount
    shipping_cost = 0
    # Initialize Razorpay client with your API keys
    # razorpay_client = razorpay.Client(auth=("your_api_key", "your_secret_key"))

    # Create a Razorpay order
    razorpay_order = razorpay_client.order.create({
        'amount': int(float(order.total_amount) * 100),  # Razorpay expects amount in paise
        'currency': 'INR',
        'payment_capture': 1,  # Auto-capture payment after order creation
    })

    # Save Razorpay order ID in your OrderModel
    order.razorpay_order_id = razorpay_order['id']
    order.status = 'Pending'
    order.save()

    # cart_items.delete()
    # cart_item.delete()
    # Render the Razorpay payment page
    context = {
        'order': order,
        'razorpay_order': razorpay_order,
        'my_order': order,
        'my_order_item_detail' : order_itemm,
        'total_order_amount':total_order_amount,
        'shipping_cost':shipping_cost
    }
    return render(request, 'payment_app/razorpay_payment.html', context)

from django.shortcuts import render
@csrf_exempt
def razorpay_payment_success(request):
    # Update order status or perform other actions
    if request.method == 'POST':
        razorpay_payment_id = request.POST.get('razorpay_payment_id')
        razorpay_order_id = request.POST.get('razorpay_order_id')
        razorpay_signature = request.POST.get('razorpay_signature')
        try:
            order = OrderModel.objects.get(razorpay_order_id=razorpay_order_id)

            # Save the Razorpay details in the order
            order.razorpay_payment_id = razorpay_payment_id
            order.razorpay_order_id = razorpay_order_id
            order.razorpay_signature = razorpay_signature

            # order status make paid
            order.status = 'Paid'
            order.save()
            
            # insure order successs then cart make empty
            user  = order.user
            print("successs: ",user)
            cart = CartModel.objects.get(user=user)
            cart_items = cart.items.all()
            cart_item = CartItemModel.objects.filter(user=user)
            

            cart_items.delete()
            cart_item.delete()
        except OrderModel.DoesNotExist:
            raise Http404("Order does not exist.")
        
    return render(request, 'payment_app/payment_success.html')

E_shopper/payment_app/templates/payment_app/payment_success.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
            </div>
            <!--signup section-->
            <div class="col-sm-4 col-sm-offset-1 ">
                <!--login form-->
                <div class="login-form" style="text-align: center; margin: 10%;">
                    <p style="font-size: x-large; font-weight:500">Payment Successful</p>
                    <p>Thank you for your payment. Your order is confirmed.</p>  
                    <a href="{% url 'home' %}" class="btn btn-default update"
                                onmouseover="this.style.color='#333';" onmouseout="this.style.color='white';"
                                style="border-radius: 10px; padding:5px 24px 5px 24px; margin-left: 0px;">Shop now</a>
                </div>
                <!--/login form-->
            </div>
            <!--signup section-->
        </div>
    </div>
</section>

{% endblock content %}

E_shopper/payment_app/templates/payment_app/razorpay_payment.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<section id='cart_items'>
	<div class="container">
		<div class="row">
			<!-- my order summery section-->
                <!-- ORDERS SUMMERY section here -->
                <div class="col-sm-12 padding-right">
                    <div class="panel-group category-products" id="accordian">
                        <div class="row" style="padding-left: 2%; margin-bottom: 0px; display: flex; justify-content: space-between; width: 100%;">
                                    <div style="width: 97%; margin-bottom: 15px; display: flex; flex-direction: column; position: relative;">
                                        <div class="review-payment">
                                            <h2 style="margin-top:0px;"> Order Review</h2>
                                        </div>
                                        <div class="table-responsive cart_info">
                                            <table class="table table-condensed">
                                                <thead>
                                                    <tr class="cart_menu">
                                                        <td class="image">Item</td>
                                                        <td class="description">Name</td>
                                                        <td class="price" style="text-align:center;">Price</td>
                                                        <td class="quantity">Quantity</td>
                                                        <td class="total" style="text-align:center;">Total</td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in my_order_item_detail %}
                                                        <tr>
                                                            <td class="cart_product" style="margin:10px;">
                                                                <a href="{% url 'product_app:productdetail' item.product.slug %}">
                                                                    <img src="{{ item.product.ProductImage.url }}" 
                                                                    alt="{{ item.product.ProductName }}" width="50"></a>
                                                            </td>
                                                            <td class="cart_description" style="white-space: normal;">
                                                                <h4><a href="{% url 'product_app:productdetail' item.product.slug %}">
                                                                    {{item.product.ProductName}}</a></h4>
                                                            </td>
                                                            <td class="cart_price" style="text-align:center;">
                                                                <p>₹{{ item.price|floatformat:"-2"|intcomma }}</p>
                                                            </td>
                                                            <td class="cart_quantity" style="margin-right:2%;text-align:center;">
                                                                <div class="btn1" style="display: inline;">
                                                                    <a class="mainbtn" href="#">{{item.quantity}}</a>
                                                                </div>
                                                            </td>
                                                            <td class="cart_total" style="text-align:center;">
                                                                <p class="cart_total_price" style="font-size:18px;">₹{{ item.subtotal|floatformat:"-2"|intcomma  }}</p>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                    {% if my_order_item_detail %}
                                                    <tr>
                                                        <td colspan="4">&nbsp;</td>
                                                        <td colspan="2">
                                                            <table class="table table-condensed total-result">
                                                                <tr>
                                                                    <td>Cart Sub Total</td>
                                                                    <td>₹{{ total_order_amount|floatformat:"-2"|intcomma }}</td>
                                                                </tr>
                                                                <tr class="shipping-cost">
                                                                    <td>Shipping Cost</td>
                                                                    <td>₹{{ shipping_cost }}</td>										
                                                                </tr>
                                                                <tr>
                                                                    <td>Total</td>
                                                                    <input type="hidden" name="totalamount" value="{{ total_order_amount|add:shipping_cost }}">
                                                                    <td><span>₹{{ total_order_amount|add:shipping_cost|intcomma }}</span></td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    {% endif %}
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div>

                        <!-- Add Razorpay payment button -->
                        <form action="{% url 'payment_app:razorpay_payment_success' %}" method="POST">
                            <script
                                src="https://checkout.razorpay.com/v1/checkout.js"
                                data-key="rzp_test_oIfjSKu51zvTk9"  
                                data-amount="{{ razorpay_order.amount }}"
                                data-currency="INR"
                                data-order_id="{{ razorpay_order.id }}"
                                data-buttontext="Pay with Razorpay"
                                data-name="E_SHOPPER"
                                data-description="Payment for Order"
                                data-image="path_to_your_logo"
                                data-prefill.name="{{ order.user.username }}"
                                data-prefill.email="{{ order.user.email }}"
                                data-theme.color="#528FF0"
                            ></script>
                            <input type="hidden" name="razorpay_payment_id" id="razorpay_payment_id">
                            <input type="hidden" name="razorpay_order_id" id="razorpay_order_id">
                            <input type="hidden" name="razorpay_signature" id="razorpay_signature">
                        </form>
                        
                        <script>
                            document.querySelector('form').addEventListener('submit', function (e) {
                                var paymentId = document.querySelector('#razorpay_payment_id');
                                var orderId = document.querySelector('#razorpay_order_id');
                                var signature = document.querySelector('#razorpay_signature');
                                e.preventDefault();

                                // Fetch Razorpay payment ID after successful payment
                                razorpayClient.on('payment.success', function (response) {
                                    paymentId.value = response.razorpay_payment_id;
                                    orderId.value = response.razorpay_order_id;
                                    signature.value = response.razorpay_signature;                

                                    // Submit the form to your server for further processing
                                    document.querySelector('form').submit();
                                },
                                // Handle payment failure
                                modal: {
                                    ondismiss: function () {
                                        // Redirect to checkout page on payment failure
                                        window.location.href = "{% url 'cart_app:checkout' %}";
                                    }
                                });

                                razorpayClient.open();
                            });
                        </script>

                        
                        <!-- css for payment button -->
                        <style>
                        .razorpay-payment-button{  
                            margin:0px 0px 30px 0px;  
                            padding:6px 12px;
                            position:relative; 
                            left:80%;
                            background: #FE980F;
                            border: none;
                            color: #fff;

                        }
                        </style>
                    </div>
                </div>
        </div>
    </div>
</section>
<!--main content-->
{% endblock content %}    