E_shopper/E_shopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
    path('category/', include('category_app.urls')),
    path('product/',include('product_app.urls')),
    path('user/',include('user_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('order/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_shopper/base_app/urls.py
from django.contrib import admin
from django.urls import path,include
from base_app import views

urlpatterns = [

    path('', views.baseview),
    path('home/',views.homeview,name='home'),
    
]

E_shopper/cart_app/urls.py
from django.contrib import admin
from django.urls import path
from cart_app.views import *

app_name = 'cart_app'

urlpatterns = [
    # for add items in cart
    path('add_to_cart/<slug:productslug>',add_to_cart, name='add_to_cart'),
    # for cart page
    path('usercart', cartView, name='cart'),
    path('deleteitem/<int:item_id>', delete_cart_item, name='delete_cart_item'),
    path('clearcart', clear_cart, name='clear_cart'),
    path('increment_cart_quantity/<int:item_id>/', increment_cart_quantity, name='increment_cart_quantity'),
    path('decrement_cart_quantity/<int:item_id>/', decrement_cart_quantity, name='decrement_cart_quantity'),

    # for checkout page
    path('checkout/', checkoutView, name='checkout'),


]

E_shopper/order_app/urls.py
from django.contrib import admin
from django.urls import path
from order_app.views import *

app_name = 'order_app'

urlpatterns = [
    # order
    path('create_order/',create_order, name='create_order'),
    path('order_detail<int:id>/',order_detail,name='order_detail'),

    # invoice
    path('invoice/<int:id>/',invoice, name='invoice'),

]

E_shopper/product_app/urls.py
from django.contrib import admin
from django.urls import path
from product_app.views import ProductView,ProductDetailView

app_name = 'product_app'

urlpatterns = [
    path('products/<slug:subcatslug>', ProductView, name='products'),
    path('productdetail/<slug:productslug>',ProductDetailView, name = 'productdetail'),
    # ... other product app URL patterns ...
]

E_shopper/user_app/urls.py
from django.contrib import admin
from django.urls import path
from user_app.views import *

app_name = 'user_app'

urlpatterns = [
    
    # signup handle
    path('signup/', signupView, name='signup'),
    path('signuphandle', handelSignup, name='signuphandle'),

    # login handle
    path('login/', loginView, name='login'),
    path('loginhandle', handleLogin, name='loginhandle'),

    # logout handle
    path('logouthandle',logouthandle, name='logouthandle'),

    # show profile 
    path('profile',profileView,name='profile'),

    # update_profile_info
    path('update_personal_info/', update_personal_info, name='update_personal_info'),

    # update email
    path('update_email/', update_email,name='update_email'),

    # update contact
    path('update_contact/', update_contact, name='update_contact'),

    # add new address
    path('add_address/', add_address, name='add_address'),

    # edit address
    path('edit_address/<int:address_id>/', edit_address, name='edit_address'),

    # delete address
    path('delete_address/<int:address_id>/', delete_address,name='delete_address'),

]

E_shopper/cart_app/models.py
from django.db import models
from django.contrib.auth.models import User
from product_app.models import ProductModel
# Create your models here.
class CartItemModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.product.ProductPrice * self.quantity
    
    def __str__(self) -> str:
        return f"{self.user.username} Has {self.product.ProductName} With {self.quantity} Quantity"
    
class CartModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItemModel)
    created_at = models.DateTimeField(auto_now_add=True)

     

E_shopper/cart_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from product_app.models import ProductModel
from cart_app.models import CartItemModel,CartModel
from user_app.models import UserProfile ,UserAddress


# Create your views here.

# this function work for specified subcategory product page,all product page,productdetail page
@login_required
def add_to_cart(request,productslug):
    user = request.user
    product = ProductModel.objects.get(slug=productslug)
    # print(product)

    # Find the user's cart or create a new one
    try:
        cart = CartModel.objects.get(user=user)
    except CartModel.DoesNotExist:
        cart = CartModel.objects.create(user=user)

    # Check if the cart item already exists for the product
    try:
        cart_item = CartItemModel.objects.get(user=user, product=product)
        cart_item_exist = True
    except CartItemModel.DoesNotExist:
        cart_item_exist = False

    # If the cart item exists, increase its quantity; otherwise, create it
    if not cart_item_exist:
        cart_item = CartItemModel.objects.create(user=user, product=product)
        cart.items.add(cart_item)
    
    subcatslug = request.GET.get('subcatslug', '')
    # print("subcatslug",subcatslug)
    
    # if product add on cart from all product page
    if subcatslug == "all":
        # redirect to all product page after add product to cart
        return redirect('product_app:products',subcatslug=subcatslug)
    # if product add on cart from productdetail page
    elif subcatslug == "productdetail":       
        # redirect to productdetail page after add product to cart
        return redirect('product_app:productdetail',productslug=productslug)
    # if product add on cart from subcategory wise product page
    else:
        # redirect to subcategory wise product page after add product to cart
        return redirect('product_app:products',subcatslug=subcatslug)

# show cart view with image,name,quantity ,subtotal
@login_required
def cartView(request):
    user = request.user

    try:
        cart = CartModel.objects.get(user=user)
    except CartModel.DoesNotExist:
        cart = CartModel.objects.create(user=user)
    
    cart_item = cart.items.all()
    # print(cart_item)

    cart_total = sum(item.subtotal() for item in cart_item)
    # print(total_price)
    shipping_cost = 0
    context = {
        'cart_items':cart_item,
        'cart': cart,
        'cart_total':cart_total,
        'shipping_cost':shipping_cost
    }

    return render(request,'cart_app/cart.html',context)

# delete specified cart item
def delete_cart_item(request, item_id):
    retpath = request.GET.get('retpath', '')
    try:
        cart_item = CartItemModel.objects.get(id=item_id)
        cart_item.delete()
    except CartItemModel.DoesNotExist:
        # Handle the case where the item doesn't exist
        pass
    if retpath == "checkout":
        return redirect('cart_app:checkout')
    return redirect('cart_app:cart')

# delte whole cart 
def clear_cart(request):
    retpath = request.GET.get('retpath', '')
    # Delete all cart items for the current user
    CartItemModel.objects.filter(user=request.user).delete()
    if retpath == "checkout":
        return redirect('cart_app:checkout')
    # Redirect back to the cart
    return redirect('cart_app:cart')

# increment item quantity
@login_required
def increment_cart_quantity(request,item_id):
    retpath = request.GET.get('retpath', '')
    try:
        cart_item = CartItemModel.objects.get(id=item_id,user=request.user)
        cart_item.quantity +=1
        cart_item.save()
    except CartItemModel.DoesNotExist:
        pass

    if retpath == "checkout":
        return redirect('cart_app:checkout')
    return redirect('cart_app:cart')

# decrement item quantity
@login_required
def decrement_cart_quantity(request, item_id):
    retpath = request.GET.get('retpath', '')
    try:
        cart_item = CartItemModel.objects.get(id=item_id, user=request.user)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
    except CartItemModel.DoesNotExist:
        pass

    if retpath == "checkout":
        return redirect('cart_app:checkout')
    return redirect('cart_app:cart')

# checkout view
@login_required
def checkoutView(request):
    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    user_addresses = UserAddress.objects.filter(user=user)
    cart = CartModel.objects.get(user=user)
    cart_item = cart.items.all()
    cart_total = sum(item.subtotal() for item in cart_item)
    shipping_cost = 0
    # retpath = request.POST.get('retpath', '')
    # selected_address_id = request.POST.get('selected_address')
    selected_address_id = request.GET.get('selected_address')
    # print("selected_address_id: ",selected_address_id)
    context = {
        'cart_items':cart_item,
        'cart': cart,
        'cart_total':cart_total,
        'shipping_cost':shipping_cost,
        'user_profile':user_profile,
        'user_addresses': user_addresses,
        'selected_address_id':selected_address_id,
    }
    
    return render(request, 'cart_app/checkout.html', context)

E_shopper/cart_app/templates/cart_app/cart.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Shopping Cart</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description">Name</td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td class="total" style="text-align:center;">
                            <a href="{% url 'cart_app:clear_cart' %}" style="color:white; text-align:right;"
                                onmouseover="this.style.color='#333'" onmouseout="this.style.color='white'">
                                <i class="fa fa-trash-o"></i> Delete All
                            </a>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% if cart_items %}
                    {% for cart_item in cart_items %}
                    <tr>
                        <td class="cart_product" style="margin:10px;">
                            <a href="{% url 'product_app:productdetail' cart_item.product.slug %}"><img
                                    src="{{ cart_item.product.ProductImage.url }}"
                                    alt="{{ cart_item.product.ProductName }}" width="50"></a>
                        </td>
                        <td class="cart_description" style="white-space: normal;">
                            <h4><a href="{% url 'product_app:productdetail' cart_item.product.slug %}">
                                {{cart_item.product.ProductName}}</a></h4>

                        </td>
                        <td class="cart_price">
                            <p>₹{{ cart_item.product.ProductPrice }}</p>
                        </td>
                        <td class="cart_quantity">
                            <div class="btn1" style="display: inline;">
                                <a class="mainusbtn" href="{% url 'cart_app:decrement_cart_quantity' cart_item.id %}">-</a>
                                <a class="mainbtn" href="#">{{cart_item.quantity}}</a>
                                <a class="plusbtn" href="{% url 'cart_app:increment_cart_quantity' cart_item.id %}">+</a>
                            </div>
                        </td>
                        <td class="cart_total">
                            <p class="cart_total_price">₹{{ cart_item.subtotal }}</p>
                        </td>
                        <td style="margin-right:2%;text-align:center;">
                            <a class="btn btn-default update" style="margin:0px;" href="{% url 'cart_app:delete_cart_item' cart_item.id %}">Delete Item</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="6" style="text-align: center; padding: 20px 0px 20px 0px;">
                            <h4>Your E-Shopper Cart is empty!</h4>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="text-align: center; padding:0px 0px 10px 0px;">
                            <a href="{% url 'home' %}" class="btn btn-default update"
                                onmouseover="this.style.color='#333';" onmouseout="this.style.color='white';"
                                style="border-radius: 10px; padding:5px 24px 5px 24px;">Shop now</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</section>
<!--/#cart_items-->

<!--total-->
{% if cart_items %}
<section id="do_action">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <div class="total_area">
                    <ul>
                        <li>Cart Sub Total <span>₹{{ cart_total }}</span></li>
                        <li>Shipping Cost <span>₹{{shipping_cost}}</span></li>
                        <li>Total <span>₹{{ cart_total|add:shipping_cost }}</span></li>
                    </ul>
                    <a class="btn btn-default update" href="{% url 'cart_app:checkout' %}">Check Out</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
<!--total-->

<style>
    .btn1 {
        width: 150px;
        height: 40px;
        padding-bottom: 20%;
    }

    .btn1 a {
        background: #FE980F;
        border: none;
        /* border-radius: 8%; */
        padding: 7px 12px;
        font-size: 1.4rem;
        color: white;
        cursor: pointer;
        outline: none;
        text-decoration: none;
        
    }

    .plusbtn,
    .mainusbtn {
        {% comment %} display: none; {% endcomment %}
        font-weight: 700;
    }
</style>
{% endblock content %}

E_shopper/cart_app/templates/cart_app/checkout.html
{% extends 'base_app/base.html' %}
{% load static %}
{% block content %}

<section id="cart_items">
<div class="container">
    <!-- breadcrumbs -->
    <div class="breadcrumbs">
        <ol class="breadcrumb" style="margin-bottom:0px;">
            <li><a href="#">Home</a></li>
            <li class="active">Check out</li>
        </ol>
    </div>

    <form method="post" action="{% url 'order_app:create_order' %}">
        {% csrf_token %}
        <div class="row">
            <!-- user login detail-->
            <div class="col-sm-3">
                {% if request.user.is_authenticated %}
                    <h3>Login <i class="fa fa-check" style="font-size: x-large; color:#FE980f"></i></h3>
                        
                    <table style="border-collapse: separate; border-spacing: 5px; border: 1px solid #ccc;">
                        <tr>
                            <th style="padding: 5px;">Name</th>
                            <td style="padding: 5px;">{{user_profile.firstname}} {{user_profile.lastname}}</td>
                        </tr>
                        <tr>
                            <th style="padding: 5px;">Phone</th>
                            <td style="padding: 5px;">{{user_profile.contact}}</td>
                        </tr>
                    </table>
                            
                    <h5><a href="{% url 'user_app:login' %}?retpath=checkout">Logout & Sign in to another account</a></h5>
                {% else %}
                    <a href="{% url 'user_app:login' %}?retpath=checkout">You need to login first</a></h5>
                {% endif %}
            </div>
            <!-- user login detail-->

            <!--Address Part-->
            <div class="col-sm-9" style="border:1px solid #ccc">
                <h3>Delivery Address</h3>
                <div class="row" style="padding-left: 2%; margin-bottom: 0px; display: flex; justify-content: space-between; width: 100%;">
                    <div style="width: 97%; margin-bottom: 15px; display: flex; flex-direction: column; position: relative;">
                        <!-- Address List-->
                        {% for address in user_addresses %}
                        <label for="custadd{{forloop.counter}}" style="cursor: pointer;">
                            <div class="address-container" style="border: 1px solid rgb(204, 204, 204); margin-top: 2%; margin-bottom: 2%; width: 100%; box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); transition: transform 0.2s;">
                                <!-- Address Card -->
                                <div class="address-card" style="position: relative; transform-style: preserve-3d; transition: transform 0.2s;">
                                    <!-- Address Header -->
                                    <div class="address-card-header" style="position: relative; margin-top: 2%;">
                                        <span class="address-type" style="margin: 35px 0px 10px 18px; padding: 2px 5px 2px 5px; font-size: 16px; font-weight: 500; color: #878787; background-color: #f0f0f0;">{{address.addresstype}}</span>
                                        <div class="form-check mr-5 mb-5" style="position: absolute; right: 12px; transform: translateY(-115%); cursor: pointer;">
                                            <input class="form-check-input" type="radio" name="address_id" id="custadd{{forloop.counter}}" value="{{address.id}}" required>
                                            <label class="dorm-check-label fw-bold" for="custadd{{forloop.counter}}">
                                                Address:{{forloop.counter}}
                                            </label>
                                        </div>
                                    </div>
                                    <!-- Address Header -->

                                    <!-- Address Body -->
                                    <div class="address-card-body" style="margin-top: 0px; padding-left: 2%; transform: rotateY(0deg); backface-visibility: hidden;">
                                        <div class="row" style="margin-bottom: 0px;">
                                            <div class="col-md-3">
                                                <div style="font-size: 18px; font-weight: 600; color: #333;">{{address.name | capfirst}}</div>
                                            </div>
                                            <div class="col-md-6">
                                                <div style="font-size: 18px; font-weight: 600; color: #333;">{{address.contact}}</div>
                                            </div>
                                        </div>
                                        <div class="row" style="margin-bottom: 0px;">
                                            <div class="col-md-12">
                                                <div style="font-size: 16px; font-weight: 400; color: #555; margin-bottom: 8px;">{{address.address}}</div>
                                            </div>
                                        </div>
                                        <div class="row" style="margin-bottom: 10px;">
                                            <div class="col-md-12">
                                                <div style="font-size: 16px; font-weight: 400; color: #555;">{{address.locality}}, {{address.city}}, {{address.state}} - <strong>{{address.pincode}}</strong></div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Address Body -->
                                </div>
                                <!-- Address Card -->
                            </div>
                        </label>
                        {% endfor %}
                        <!-- Address List-->
                    </div>
                </div>
            </div>
            <!--Address Part-->
            
        </div>

        <div class="review-payment">
            <h2 style="margin-top:0px;">Review & Payment</h2>
        </div>

        <!-- cart detail table -->
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td class="total" style="text-align:center;">
                            <a href="{% url 'cart_app:clear_cart' %}?retpath=checkout" style="color:white; text-align:right;"
                                onmouseover="this.style.color='#333'" onmouseout="this.style.color='white'">
                                <i class="fa fa-trash-o"></i> Delete All
                            </a>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% if cart_items %}
                        {% for cart_item in cart_items %}
                            <tr>
                                <td class="cart_product" style="margin:10px;">
                                    <a href="{% url 'product_app:productdetail' cart_item.product.slug %}">
                                        <img src="{{ cart_item.product.ProductImage.url }}" 
                                        alt="{{ cart_item.product.ProductName }}" width="50"></a>
                                </td>
                                <td class="cart_description" style="white-space: normal;">
                                    <h4><a href="{% url 'product_app:productdetail' cart_item.product.slug %}">
                                        {{cart_item.product.ProductName}}</a></h4>
                                </td>
                                <td class="cart_price">
                                    <p>₹{{ cart_item.product.ProductPrice }}</p>
                                </td>
                                <td class="cart_quantity">
                                    <div class="btn1" style="display: inline;">
                                        <a class="mainusbtn" href="{% url 'cart_app:decrement_cart_quantity' cart_item.id %}?retpath=checkout">-</a>
                                        <a class="mainbtn" href="#">{{cart_item.quantity}}</a>
                                        <a class="plusbtn" href="{% url 'cart_app:increment_cart_quantity' cart_item.id %}?retpath=checkout">+</a>
                                    </div>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">₹{{ cart_item.subtotal }}</p>
                                </td>
                                <td style="margin-right:2%;text-align:center;">
                                    <a class="btn btn-default update" style="margin:0px;" href="{% url 'cart_app:delete_cart_item' cart_item.id %}?retpath=checkout">Delete Item</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="6" style="text-align: center; padding: 20px 0px 20px 0px;">
                                <h4>Your E-Shopper Cart is empty!</h4>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="6" style="text-align: center; padding:0px 0px 10px 0px;">
                                <a href="{% url 'home' %}" class="btn btn-default update"
                                    onmouseover="this.style.color='#333';" onmouseout="this.style.color='white';"
                                    style="border-radius: 10px; padding:5px 24px 5px 24px;">Shop now</a>
                            </td>
                        </tr>
                    {% endif %}
                    {% if cart_items %}
                    <tr>
                        <td colspan="4">&nbsp;</td>
                        <td colspan="2">
                            <table class="table table-condensed total-result">
                                <tr>
                                    <td>Cart Sub Total</td>
                                    <td>₹{{ cart_total }}</td>
                                </tr>
                                <tr class="shipping-cost">
                                    <td>Shipping Cost</td>
                                    <td>₹{{shipping_cost}}</td>										
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <input type="hidden" name="totalamount" value="{{ cart_total|add:shipping_cost }}">
                                    <td><span>₹{{ cart_total|add:shipping_cost }}</span></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>
        <!-- cart detail table -->

        <!-- payment option -->
        <div class="payment-options" style="margin-bottom:20px; position: relative; left: 80%;">
            <input type="radio" id="Cod" name="PaymentType" value="Cash On Delivary" class="form-check-input" style="margin-right: 5px;" required>
            <label for="Cod" class="form-check-label" style="font-size: 14px; font-weight: 500; color: #878787;">COD</label>
            <input type="radio" id="Online" name="PaymentType" value="Online" class="form-check-input" style="margin-right: 5px; margin-left:5%;" required >
            <label for="Online" class="form-check-label" style="font-size: 14px; font-weight: 500; color: #878787;">Online</label>
        </div>
        <!-- payment option -->

        <!-- payment button-->
        <div class="row">
            <button type="submit" id="payment" class="btn btn-primary" style="margin:0px 0px 30px 0px;  position:relative; left:80%;">Proceed to Payment</button>
        </div>
        <!-- payment button-->
    </form>
    {% if messages %}
    <script>
        {% for message in messages %}
            alert("{{ message }}")
        {% endfor %}
    </script>
    {% endif %}
</div>
<style>
    .btn1 {
        width: 150px;
        height: 40px;
        padding-bottom: 20%;
    }

    .btn1 a {
        background: #FE980F;
        border: none;
        /* border-radius: 8%; */
        padding: 7px 12px;
        font-size: 1.4rem;
        color: white;
        cursor: pointer;
        outline: none;
        text-decoration: none;
        
    }

    .plusbtn,
    .mainusbtn {
        /* display: none; */
        font-weight: 700;
    }
</style>
{% endblock content %}